### ISSUE TITLE
ERP website changes

### ISSUE THREAD

**Issue by Demongodmax** [BIT-Lalpur-App/BIT-App#157]
Hello Devs,
The erp portal website link that is given in the Bit app is the old one and the institute has launched a new website recently so, if you can please chack and try to link the new ebsite through the app it will be very helpful.

![Screenshot_20230814-092733_Chrome.jpg](https://github.com/BIT-Lalpur-App/BIT-App/assets/132573533/3894dab5-f254-4f18-9627-d128ca7c73c9)

New website : https://erpportal.bitmesra.ac.in/login.htm

Thank you for making such a helpul app!

**Comment by aiyu-ayaan** [comment]
We're aware of the old ERP portal website link in the Bit app and we're working on linking the new website through the app as soon as possible. Thanks for your patience!
